# Generated by Django 3.0.6 on 2020-07-11 02:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinaciones',
            fields=[
                ('cve_co', models.IntegerField(primary_key=True, serialize=False)),
                ('cz', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'coordinaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('cvegeo', models.IntegerField(primary_key=True, serialize=False)),
                ('loc', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'localidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('cvegeo', models.IntegerField(primary_key=True, serialize=False)),
                ('mun', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'municipios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EDOMEX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_ent', models.CharField(max_length=2)),
                ('cve_mun', models.CharField(max_length=3)),
                ('cvegeo', models.CharField(max_length=5)),
                ('nomgeo', models.CharField(max_length=80)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Edomex',
            },
        ),
        migrations.CreateModel(
            name='Unidad_Operativa',
            fields=[
                ('Clave_Unidad_Operativa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Tipo_Unidad_Operativa', models.CharField(choices=[('Circulo de estudio', 'Circulo de estudio'), ('Punto de encuentro', 'Punto de encuentro'), ('Plaza comunitaria', 'Plaza comunitaria')], max_length=30)),
                ('Nombre_Unidad_Operativa', models.CharField(max_length=100)),
                ('Domicilio', models.CharField(max_length=100)),
                ('Colonia', models.CharField(max_length=100)),
                ('Codigo_Postal', models.CharField(max_length=10)),
                ('Geolocalización', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('Coordinación', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escuelas.Coordinaciones')),
                ('Municipio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='escuelas.Municipios')),
            ],
            options={
                'verbose_name_plural': 'Unidad Operativa',
            },
        ),
    ]
